version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: brev-ly-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d brevly"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: